# Assignment

In [1]:
import numpy as np

Q1. Write the NumPy program to create a 2d array with 6 on the border
and 0 inside?

    Expected OutputOriginal array-
    [ [6 6 6 6 6]
     [ 6 6 6 6 6]
     [ 6 6 6 6 6 ]
    [ 6 6 6 6 6 ]
    [ 6 6 6 6 ] ].
    6 on the border and 0 inside in the array-
    [[ 6 6 6 6 6]
    [ 6 0 0 0 6]
    [ 6 0 0 0 6]
    [ 6 0 0 0 6]
    [ 6 6 6 6 6]].

In [35]:
matr = 6 * np.ones((6,6))
print('original array \n{}'.format(matr))
matr[:,1:-1]=0
print('updated array \n {}'.format(matr))

original array 
[[6. 6. 6. 6. 6. 6.]
 [6. 6. 6. 6. 6. 6.]
 [6. 6. 6. 6. 6. 6.]
 [6. 6. 6. 6. 6. 6.]
 [6. 6. 6. 6. 6. 6.]
 [6. 6. 6. 6. 6. 6.]]
updated array 
 [[6. 0. 0. 0. 0. 6.]
 [6. 0. 0. 0. 0. 6.]
 [6. 0. 0. 0. 0. 6.]
 [6. 0. 0. 0. 0. 6.]
 [6. 0. 0. 0. 0. 6.]
 [6. 0. 0. 0. 0. 6.]]


Q2. Write the NumPy program to create a 8x8 matrix and fill it with the
checkerboard pattern?
    
    Checkerboard pattern-
    [[3 9 3 9 3 9 3 9]
    [9 3 9 3 9 3 9 3]
    [3 9 3 9 3 9 3 9]
    [9 3 9 3 9 3 9 3]
    [3 9 3 9 3 9 3 9]
    [9 3 9 3 9 3 9 3]
    [3 9 3 9 3 9 3 9]
    [9 3 9 3 9 3 9 3]].

In [23]:

a = np.ones([8,8])
x[1::2,::2] = 3
x[::2,1::2] = 9
print(x)

[[0 9 0 9 0 9 0 9]
 [3 0 3 0 3 0 3 0]
 [0 9 0 9 0 9 0 9]
 [3 0 3 0 3 0 3 0]
 [0 9 0 9 0 9 0 9]
 [3 0 3 0 3 0 3 0]
 [0 9 0 9 0 9 0 9]
 [3 0 3 0 3 0 3 0]]


In [36]:
def printcheckboard(n): 
      
    print("Checkerboard pattern:") 
    # create a n * n matrix 
    x = np.zeros((n, n), dtype = int) 
    np.fill_diagonal(x,3)
    # fill with 1 the alternate rows and columns 
    x[0::2, ::2] = 3
    x[1::2, 0::2] = 9
      
    # print the pattern 
    for i in range(n): 
        for j in range(n): 
            print(x[i][j], end =" ")  
        print()  
  
# driver code 
n = 8
printcheckboard(n) 

Checkerboard pattern:
3 0 3 0 3 0 3 0 
9 3 9 0 9 0 9 0 
3 0 3 0 3 0 3 0 
9 0 9 3 9 0 9 0 
3 0 3 0 3 0 3 0 
9 0 9 0 9 3 9 0 
3 0 3 0 3 0 3 0 
9 0 9 0 9 0 9 3 


Q3. Write the NumPy program to create an empty and a full array.
 
     Expected Output-
    [[4.45057637e-308 1.78021527e-306 8.45549797e-307 1.37962049e-306]
    [1.11260619e-306 1.78010255e-306 9.79054228e-307 4.45057637e-308]
    [8.45596650e-307 9.34602321e-307 4.94065646e-322 0.00000000e+000]]
    [[6 6 6]
    [6 6 6]
    [6 6 6]]


In [47]:
a = np.empty((4,4))
y = np.full((3,3),6)
print('empty matrix\n',a)
print('full matrix\n',y)

empty matrix
 [[4.67839225e-310 0.00000000e+000 2.41907520e-312 2.37663529e-312]
 [2.22809558e-312 2.46151512e-312 6.79038654e-313 2.35541533e-312]
 [2.46151512e-312 6.79038654e-313 2.35541533e-312 6.79038654e-313]
 [2.14321575e-312 2.22809558e-312 2.14321575e-312 6.95080941e-310]]
full matrix
 [[6 6 6]
 [6 6 6]
 [6 6 6]]


Q4. Write the NumPy program to convert the values of Centigrade
degrees into the Fahrenheit degrees and the centigrade values are
stored in the NumPy array.
    
    Sample Array -[0, 12, 45.21 ,34, 99.91]
    Expected OutputValues in Fahrenheit degrees-
    [ 0. 12. 45.21 34. 99.91]
    Values in Centigrade degrees-
    [-17.77777778 -11.11111111 7.33888889 1.11111111 37.72777778]

In [48]:
sample = [0,12,45.21,34,99.91]
sam = np.array(sample)
print(5*sam/9 - 5*32/9)

[-17.77777778 -11.11111111   7.33888889   1.11111111  37.72777778]


Q5. Write the NumPy program to find the real and imaginary parts of an
array of complex numbers?

    Expected OutputOriginal array [ 1.00000000+0.j 0.70710678+0.70710678j]
    Real part of the array-
    [ 1. 0.70710678]
    Imaginary part of the array-
    [ 0. 0.70710678]

In [62]:
a = [1.0000000000+0.j,0.70710678+0.70710678j]
am = np.array(a)
print(am.real[:],  '\n imaginary part is\n',am.imag[:])

[1.         0.70710678] 
 imaginary part is
 [0.         0.70710678]


Q6. Write the NumPy program to test whether each element of a 1-D
array is also present in the second array?

    Expected OutputArray1: [ 0 10 20 40 60]
    Array2: [0, 40]
    Compare each element of array1 and array2
    [ True False False True False]


In [69]:
one = np.array([0,10,20,40,60])
two = (0,40)
print('comparing each element of array 1 and array2 \n')
np.in1d(one,two)

comparing each element of array 1 and array2 



array([ True, False, False,  True, False])

Q7. Write the NumPy program to find common values between two
arrays?
    
    Expected OutputArray1: [ 0 10 20 40 60]
    Array2: [10, 30, 40]
    Common values between two arrays-
    [10 40]

In [70]:
arr1 = np.array([0,10,20,40,60])
arr2 = np.array([10,30,40])
np.intersect1d(arr1,arr2)

array([10, 40])

Q8. Write the NumPy program to get the unique elements of an array?

    Expected OutputOriginal array-
    [10 10 20 20 30 30]
    Unique elements of the above array-
    [10 20 30]
    P a g e 14 | 44
    Original array-
    [[1 1]
    [2 3]]
    Unique elements of the above array-
    [1 2 3]

In [87]:
a1 = np.array([10,10,20,20,30,30])
np.unique(a1)

array([10, 20, 30])

Q9. Write the NumPy program to find the set exclusive-or of two arrays.
Set exclusive-or will return the sorted, unique values that are in
only one (not both) of the input arrays?

    Array1- [ 0 10 20 40 60 80]
    Array2- [10, 30, 40, 50, 70]
    Unique values that are in only one (not both) of the input arrays-
    [ 0 20 30 50 60 70 80]

In [89]:
a1 = [ 0 ,10, 20, 40, 60, 80]
a2 = [10, 30, 40, 50, 70]
np.setxor1d(a1,a2)

array([ 0, 20, 30, 50, 60, 70, 80])

Q10. Write the NumPy program to test if all elements in an array
evaluate to True ?
 
Note: 0 evaluates to False in NumPy

In [96]:
print(np.all([[True,False],[True,True]]))
print(np.all([[True,True],[True,True]]))
print(np.all([3,-1,1,0]))
print(np.all([[1,2]]))

False
True
False
True


Q11. Write the NumPy program to test whether any array element along
the given axis evaluates to True?
 
Note: 0 evaluates to False in NumPy

In [111]:
print(np.any([[False,False],[False,False]]))
print(np.any([[True,True],[True,True]]))
print(np.any([0]))

False
True
False


Q12. Write the NumPy program to construct an array by repeating?

    Sample array- [1, 2, 3, 4]
    Expected OutputOriginal array
    [1, 2, 3, 4]
    Repeating 2 times
    [1 2 3 4 1 2 3 4]
    Repeating 3 times
    [1 2 3 4 1 2 3 4 1 2 3 4]

In [113]:
a = [1,2,3,4]
b = np.tile(a,3)
print(b)

[1 2 3 4 1 2 3 4 1 2 3 4]


Q13. Write the NumPy program to find the indices of the maximum and
minimum values with the given axis of an array?

    Original array- [1 2 3 4 5 6]
    Maximum Values- 5
    Minimum Values- 0

In [117]:
array = [1 ,2 ,3, 4, 5, 6]
print('maximi=um value is',np.argmax(array))
print('minimum value is ',np.argmin(array))

maximi=um value is 5
minimum value is  0


Q14. Write the NumPy program compare two arrays using numpy?

    Array a- [1 2]
    Array b- [4 5]
    a > b
    [False False]
    a >= b
    [False False]
    a < b
    [ True True]
    a <= b
    [ True True]


In [122]:
a = [1,2]
b = [4,5]
print(np.greater(a,b))
print(np.greater_equal(a,b))
print(np.less(a,b))
print(np.less_equal(a,b))

[False False]
[False False]
[ True  True]
[ True  True]


Q15. Write the NumPy program to sort an along the first, last axis of an
array?

    Sample array- [[2,5],[4,4]]
    Expected OutputOriginal array:
    [[4 6]
    [2 1]]
    Sort along the first axis:
    [[2 1]
    [4 6]]
    Sort along the last axis-
    [[1 2]
    [4 6]]

In [5]:
sample = np.array([[4,6],[2,1]])
a = np.sort(sample,axis=0)
print('sort in 1st axis\n',a)
b = np.sort(a,axis =0)
print('sort in 2nd axis \n',b)

sort in 1st axis
 [[2 1]
 [4 6]]
sort in 2nd axis 
 [[2 1]
 [4 6]]


Q16. Write the NumPy program to sort pairs of first name and last name
return their indices (first by last name, then by first name).

    first_names - ( Betsey, Shelley, Lanell, Genesis, Margery )
    last_names - ( Battle, Brien, Plotner, Stahl, Woolum )
    Expected Output-
    [1 3 2 4 0]

In [15]:
first_names = ( 'Margery','Betsey','Shelley', 'Lanell' ,' Genesis' )
last_names = ('Woolum','Battle', 'Plotner','Brien','Stahl'  )

a = np.lexsort((first_names,last_names))
print(a)

[1 3 2 4 0]


Q17. Write the NumPy program to get the values and indices of the
elements that are bigger than 10 in the given array?

    Original array-
    [[ 0 10 20]
    [20 30 40]]
    Values bigger than 10 = [20 20 30 40]
    Their indices are (array([0, 1, 1, 1]), array([2, 0, 1, 2]))

In [104]:
a = np.array([[0,10,20],[20,30,40]])
print('values bigger than 10 are',a[a>10])
print('indices are',np.nonzero(a>10))

values bigger than 10 are [20 20 30 40]
indices are (array([0, 1, 1, 1]), array([2, 0, 1, 2]))


Q18. Write the NumPy program to find the memory size of a NumPy
array?

    Expected Output128 bytes


In [98]:
a = np.zeros((4,4))
print('%d bytes'%(a.size*a.itemsize))

128 bytes


## Great Job!